---
title: "Fund Country Weights"
resource_files:
- worldFundCountryWeights.RDat
runtime: shiny_prerendered
output:
  flexdashboard::flex_dashboard:
    orientation: rows

---

```{r setup, include = FALSE}
# Load packages and initialize data here
library(flexdashboard)
library(dygraphs)
library(leaflet)
library(DT)
library(data.table)
library(dplyr)
```


```{r data, cache = TRUE, include = FALSE}
##load data
load('worldFundCountryWeights.RDat')

##build  map
emerging_marketPal <- colorQuantile("Purples", world_fund_country_weights$emerging_market, n = 20)

emerging_marketPopup <- paste0("<strong>Country: </strong>", 
                world_fund_country_weights$name,
                "<br><strong> Country Weight: </strong>", 
                world_fund_country_weights$emerging_market, "%")

leaf_world_emerging <- leaflet(world_fund_country_weights) %>%
  addProviderTiles("CartoDB.Positron") %>% 
  setView(lng =  20, lat =  15, zoom = 2) %>%
      addPolygons(stroke = FALSE, smoothFactor = 0.2, fillOpacity = .7,
      color =~emerging_marketPal(emerging_market), layerId = ~name, popup = emerging_marketPopup)
```


Fund Weights with Dynamic Shading {data-orientation=rows}
=====================================

Column {.sidebar data-width=200}
-------------------------------------
  
```{r, context = "render"}
helpText("Choose a radio button to change the way the map is shaded.")

radioButtons("fund", "Fund",
               c("Emerging Markets ETF" = "emerging_market",
                 "Total International ETF" = "international",
                 "International Infrastructure ETF" = "infrastructure",
                 "Asia Ex Japan ETF" = "asia_ex_japan", 
                 "Europe ETF" = "europe"))
```

Row {data-height=650}
-------------------------------------

### Fund Country Weights

```{r, context = "render", echo = FALSE}

leafletOutput("fundMap")
```

```{r, context = "server"}

output$fundMap <- renderLeaflet({
    leaf_world_emerging
  })

observeEvent(input$fund, {
      #  let's create a new palette based on the input selected
      indicator <- as.character(input$fund)
      
      Pal <- colorNumeric( 
        palette = "Greens",
        domain = world_fund_country_weights[[indicator]]
        )
      
      dynamicPopup <- paste0("<strong>Country: </strong><br>", 
                     world_fund_country_weights$name,
                     "<br><strong> Country Weight: </strong>",
                     world_fund_country_weights[[indicator]], "%"
                    )
      
      leafletProxy( "fundMap", data = world_fund_country_weights) %>%
        removeShape( layerId = ~name ) %>%
        addProviderTiles("CartoDB.Positron") %>%   
        addPolygons(stroke = TRUE, color = "black", weight = .4, opacity = 1.0, 
                    smoothFactor = 0.5, fill = TRUE, fillColor = ~Pal(world_fund_country_weights[[indicator]]), 
                    fillOpacity = .8, layerId = ~name, popup = dynamicPopup)  #%>% 
        #addLegend(position = "bottomright", pal = Pal, values = world_fund_country_weights[[indicator]],
         #     layerId = "legend", opacity = 1 )
      
    })

```

Row {.tabset .tabset-fade}
--------------------------------

###  Data Table 

```{r, context = "render", echo = FALSE}
dataTableOutput('table')
```

```{r, context = "server"}

clickedCountry <- eventReactive(input$fundMap_shape_click, {
     return(input$fundMap_shape_click$id)
     })

output$table <- renderDataTable({

  df <- reactive({
    x <- get(input$fund)
    x[4] <- x[4]/100
    x
  })
  
  df <- data.table(df())
  subdf <- subset(df, Country == as.character(clickedCountry())) 
  subdf$Country <- NULL
  
  datatable(head(subdf, n =20), fillContainer = TRUE, class = 'cell-border stripe', 
            caption = as.character(clickedCountry()), options = list(dom = 't', pageLength = 20)) %>% 
    formatPercentage(3, 2)
})
```

### Country Weights

```{r, context = "render", echo = FALSE}
dataTableOutput('countryWeightsTable')
```

```{r, context = "server"}

output$countryWeightsTable <- renderDataTable({

fund <- reactive({
    x <- get(paste(input$fund, "_country_weights", sep=""))
    x[2] <- x[2]/100
    x
  })

fund_countries <- 
  datatable(fund(), colnames = c('Country', 'Weight(%)'), fillContainer = TRUE, 
            class = 'cell-border stripe', 
            options = list(columnDefs = list(list(className = 'dt-center', targets = 0:2))))  %>% 
  formatPercentage(2, 2) 
#%>%  formatStyle(2, textAlign = 'center')
  
#datatable(head(fund, n =20), colnames = c('Country', 'Weight(%)'), fillContainer = TRUE,
 #            options = list(dom = 't', pageLength = 20))
#head(fund(), n = 6, digits = 2)
#
})
#, striped = TRUE, bordered = TRUE,  
 #                hover = TRUE, width = '10cm')
```
